#! /bin/bash
# Script to do a custom git build which might
# be a,
#
#    1. Global build
#    2. Test build
#
# 'Test build' is the default
#
# A 'Global build' hides the other git executable's,
# when executed for the first time.

make clean

if [ "$1" == "global" ] || [ "$1" == "g" ]
then
  echo "WARNING: Doing a global build."
  echo "This might 'hide' existing git installation under 'hgit'"
  echo "Read the script for more info"
  . BUILD-CUSTOM-GLOBAL
else
  . BUILD-CUSTOM-TEST
fi
