#!/bin/bash
# Script that does 'builds' git and
# adds custom alias to test executable

. BUILD-CUSTOM-COMMON

# Done only during the first time
setup_alias() {
  TEST_GIT="$(pwd)/bin-wrappers/git"
  TEST_GIT_DEBUG="$(pwd)/git"
  TEST_GIT_ALIAS='tgit'

  add_to_bashrc '\n# Custom alias for test executable'
  add_to_bashrc "alias $TEST_GIT_ALIAS=\"$TEST_GIT\""
  add_to_bashrc "# Export variable that denotes existence of '$TEST_GIT_ALIAS' alias"
  add_to_bashrc 'export CUSTOM_TEST_GIT_ALIAS=1'
  add_to_bashrc "# Export variable that could be used in places where aliases don't work"
  add_to_bashrc "export TGIT=\"$TEST_GIT_DEBUG\""
}

# Assumes configurations such as NO_GETTEXT=1 etc.
# have been specified in config.mak
if make
then
  if [ -z "$CUSTOM_TEST_GIT_ALIAS" ]
  then
    notify 'Adding alias for test build'
    setup_alias
  fi
else
  exit $?
fi
