#!/bin/bash
# Script to do a custom git 'installation'

. BUILD-CUSTOM-COMMON

CUSTOM_BUILD_LOCATION='${HOME}/.local'

# Add custom alias for git that gets hidden
# due to this installation
setup_alias() {

  # Assumes git is present for sure
  get_current_git() {
    echo "$(type -p git)"
  }

  HIDDEN_GIT_ALIAS="hgit"
  CURR_GIT=$(get_current_git)
  notify "adding alias $HIDDEN_GIT_ALIAS for $CURR_GIT"
  add_to_bashrc "\n# Custom alias existing git that would get hidden"
  add_to_bashrc "alias $HIDDEN_GIT_ALIAS=\"$CURR_GIT\""
  add_to_bashrc "alias git=\"$1\""
  add_to_bashrc "# Define variable that denotes existence of 'git' alias"
  add_to_bashrc "export CUSTOM_GLOBAL_GIT_ALIAS=1"

}

warn "Doing a global build."
warn "This might 'hide' existing git installation under 'hgit'"
warn "Read the script for more info"

# Assumes configurations such as prefix etc.
# have been specified in config.mak
make prefix=$CUSTOM_BUILD_LOCATION
make prefix=$CUSTOM_BUILD_LOCATION install

if [ $? == 0 ] && (type git 1>/dev/null 2>/dev/null) && [ -z "$CUSTOM_GLOBAL_GIT_ALIAS" ]
then
  CUSTOM_GIT_BINARY="$CUSTOM_BUILD_LOCATION/bin/git"
  setup_alias $CUSTOM_GIT_BINARY
fi
