#! /bin/bash
# Script to do a custom git build which might
# be a,
#
#    1. Global build
#    2. Test build
#
# 'Test build' is the default
#
# A 'Global build' hides the other git executable's,
# when executed for the first time.

build () {
  if [ "$1" == "global" ] || [ "$1" == "g" ]
  then
   . BUILD-CUSTOM-GLOBAL
  else
   . BUILD-CUSTOM-TEST
  fi

}

if [ "$1" == "clean" ] || [ "$1" == "c" ]
then
  make -C .. clean
  build "$2"
else
  build "$1"
fi
