#!/bin/bash
# Script that does 'builds' git and
# adds custom alias to test executable

. BUILD-CUSTOM-COMMON

# Done only during the first time
setup_alias() {
  TEST_GIT="$(pwd)/git"
  TEST_GIT_ALIAS="tgit"

  add_to_bashrc "\n# Custom alias for test executable"
  add_to_bashrc "alias $TEST_GIT_ALIAS=\"$TEST_GIT\""
  add_to_bashrc "# Define variable that denotes existence of '$TEST_GIT_ALIAS' alias"
  add_to_bashrc "export CUSTOM_TEST_GIT_ALIAS=1"
}

build() {
  make $BUILD_OPTS
}

build

if [ $? == 0 ] && [ -z "$CUSTOM_TEST_GIT_ALIAS" ]
then
  notify "Adding alias for test build"
  setup_alias
fi
